# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fetch.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65tch.proto\x12\x05\x66\x65tch\"!\n\rFetch_Request\x12\x10\n\x08\x61nime_id\x18\x01 \x01(\t\"3\n\x0e\x46\x65tch_Response\x12\x13\n\x0b\x61nime_title\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t2E\n\rFetch_Service\x12\x34\n\x05\x46\x65tch\x12\x14.fetch.Fetch_Request\x1a\x15.fetch.Fetch_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fetch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FETCH_REQUEST']._serialized_start=22
  _globals['_FETCH_REQUEST']._serialized_end=55
  _globals['_FETCH_RESPONSE']._serialized_start=57
  _globals['_FETCH_RESPONSE']._serialized_end=108
  _globals['_FETCH_SERVICE']._serialized_start=110
  _globals['_FETCH_SERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
